Revert "Always try and enable the new_uninit feature."
This reverts commit d678fbfb4802deac0258a9a53eac960d6e6e1bc5.

The original change broke Chromium:

```
error[E0725]: the feature `new_uninit` is not in the list of allowed features
  --> ../../third_party/boringssl/src/rust/bssl-crypto/src/lib.rs:28:12
   |
28 | #![feature(new_uninit)]
   |            ^^^^^^^^^^
```

Change-Id: I6732a720a5705cfe7b0219b5d9d02a911af0f89a
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/74987
Auto-Submit: Adam Langley <agl@google.com>
Commit-Queue: Adam Langley <agl@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: David Benjamin <davidben@google.com>