Use `foo/mod.rs` files instead of `foo.rs` for modules with submodules.
Exception: Avoid doing this for `arithmetic::bigint` for now, as that
will be refactored separately.

```
find src -type d '!' -exec test -e "{}/mod.rs" ';' -print
```